## Animal(Class) is-a Object
class Animal(object):
    def SayHi(self):
        print "Animal greeting"
## Dog(Class) is a Animal(Class)
class Dog(Animal):
    def __init__(self, name):
        ##Dog(Class) has a Name(Object)
        self.name = name
##Cat(Class) is a Animal(Class)
class Cat(Animal):
    def __init__(self, name):
        ## Cat(Class) has a name(object) and is indistiguishable from a dog.    
        self.name = name 
    def SayMeow(self):
        print "Meow"

##Person(Class) is an object
class Person(object):
    def __init__(self, name):
        ##Person has a name
        self.name = name

        ##Person could have a pet
        self.pet = None   
    def SayHi(self):
        print "hi!"
    def SayBye(self):
        print "person says bye!"        
##Employee(Class) is a Person(Class)
class Employee(Person):
    def __init__(self, name, salary):
        ##Employee has a name generated by exploiting his being a Person
        super(Employee, self).__init__(name)
        ##Employee has a salary(Object)
        self.salary = salary
    def SayBye(self):
        print "Employee says bye!"
##More of the same....##

##rover is a dog annoyingly named Rover with different capitalization
rover = Dog('Rover')

##Satan(object) is a cat(class) which is a pet(class)
satan = Cat("Satan")

##Mary is a person
mary = Person("Mary")

##Mary has a pet (a cat named satan)
mary.pet = satan

##Frank is an employee who has a salary and a name
frank = Employee('frank', 120000)


##Both employees and people can say hi because both are people!
frank.SayHi()
mary.SayHi()

##Cats can say hi as they are animals!
satan.SayHi()

#They dont both say the same bye though, because employee has its own bye!
frank.SayBye()
mary.SayBye()

#In his core frank is a person after all.
super(Employee, frank).SayBye()

#multiple inheritance test:
class Hybrid(Person, Cat):
    def __init__(self, name):
        self.name = name

bilbo = Hybrid('Bilbo')

##Bilbo can Meow AND say bye! He is a cat man!
bilbo.SayMeow()
bilbo.SayBye()
##Bilbo says Hi as a person. because he is a person first and a cat second
bilbo.SayHi()






